-- ============================================================
--  Student Admission Portal — Core Entities
--  Tables: schools, profiles, sub_admins, parent_links
-- ============================================================

-- ---------------------------------------------------
-- 1. SCHOOLS
-- ---------------------------------------------------
CREATE TABLE IF NOT EXISTS public.schools (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  registration_id TEXT UNIQUE NOT NULL,  -- Generated by super admin (e.g. SCH-0001)
  name            TEXT NOT NULL,
  email           TEXT,
  address         TEXT,
  phone           TEXT,
  user_id         UUID REFERENCES auth.users(id) ON DELETE SET NULL,  -- Linked school admin
  is_approved     BOOLEAN NOT NULL DEFAULT false,
  created_by      UUID REFERENCES auth.users(id) ON DELETE SET NULL,  -- Super admin who created it
  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.schools ENABLE ROW LEVEL SECURITY;

-- Super admins can manage schools
CREATE POLICY "Super admins manage schools"
  ON public.schools FOR ALL
  USING (
    public.user_has_role('super_admin')
  )
  WITH CHECK (
    public.user_has_role('super_admin')
  );

-- School admins can view their own school record
CREATE POLICY "School admins view own school"
  ON public.schools FOR SELECT
  USING (user_id = auth.uid());

-- Unauthenticated users can check if a school ID exists (for registration)
CREATE POLICY "Anyone can check school ID"
  ON public.schools FOR SELECT
  USING (true);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_schools_registration_id ON public.schools(registration_id);
CREATE INDEX IF NOT EXISTS idx_schools_user_id ON public.schools(user_id);
CREATE INDEX IF NOT EXISTS idx_schools_approved ON public.schools(is_approved);

-- ---------------------------------------------------
-- 2. PROFILES
-- ---------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
  id          UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name   TEXT NOT NULL,
  email       TEXT NOT NULL,
  role        TEXT NOT NULL DEFAULT 'student'
              CHECK (role IN ('super_admin','admin','sub_admin','teacher','student','parent','accountant')),
  school_id   UUID REFERENCES public.schools(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Everyone can read own profile
CREATE POLICY "Users read own profile"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

-- Users insert own profile
CREATE POLICY "Users insert own profile"
  ON public.profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

-- Users update own profile
CREATE POLICY "Users update own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

-- Admins can read all profiles in their school
CREATE POLICY "Admins read all profiles"
  ON public.profiles FOR SELECT
  USING (
    public.user_has_role('super_admin')
    OR public.user_has_role('admin')
    OR public.user_has_role('sub_admin')
  );

-- Auto-profile trigger on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  user_role TEXT;
  user_school_id UUID;
BEGIN
  -- Determine role from raw_user_meta_data
  user_role := COALESCE(NEW.raw_user_meta_data->>'role', 'student');
  
  -- Get school_id from metadata if provided
  IF NEW.raw_user_meta_data->>'school_id' IS NOT NULL THEN
    user_school_id := (NEW.raw_user_meta_data->>'school_id')::UUID;
  END IF;
  
  INSERT INTO public.profiles (id, full_name, email, role, school_id)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    COALESCE(NEW.email, ''),
    user_role,
    user_school_id
  )
  ON CONFLICT (id) DO UPDATE SET
    school_id = COALESCE(user_school_id, profiles.school_id),
    role = COALESCE(user_role, profiles.role);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ---------------------------------------------------
-- 3. SUB_ADMINS
-- ---------------------------------------------------
CREATE TABLE IF NOT EXISTS public.sub_admins (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  registration_id TEXT UNIQUE NOT NULL,  -- Generated by school admin (e.g. SA-0001)
  full_name       TEXT NOT NULL,
  email           TEXT,
  user_id         UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  is_approved     BOOLEAN NOT NULL DEFAULT false,
  created_by      UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  school_id       UUID REFERENCES public.schools(id) ON DELETE CASCADE,
  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.sub_admins ENABLE ROW LEVEL SECURITY;

-- Super admins can manage all sub_admins
CREATE POLICY "Super admins manage sub_admins"
  ON public.sub_admins FOR ALL
  USING (
    public.user_has_role('super_admin')
  )
  WITH CHECK (
    public.user_has_role('super_admin')
  );

-- School admins can manage sub_admins within their school
CREATE POLICY "School admins manage sub_admins"
  ON public.sub_admins FOR ALL
  USING (
    public.user_has_role('admin')
    AND public.user_belongs_to_school(sub_admins.school_id)
  )
  WITH CHECK (
    public.user_has_role('admin')
    AND public.user_belongs_to_school(sub_admins.school_id)
  );

-- Sub admins can view their own record
CREATE POLICY "Sub admins view own record"
  ON public.sub_admins FOR SELECT
  USING (user_id = auth.uid());

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sub_admins_registration_id ON public.sub_admins(registration_id);
CREATE INDEX IF NOT EXISTS idx_sub_admins_user_id ON public.sub_admins(user_id);
CREATE INDEX IF NOT EXISTS idx_sub_admins_approved ON public.sub_admins(is_approved);
CREATE INDEX IF NOT EXISTS idx_sub_admins_school_id ON public.sub_admins(school_id);

-- ---------------------------------------------------
-- 4. PARENT LINKS
-- ---------------------------------------------------
CREATE TABLE IF NOT EXISTS public.parent_links (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  student_id     TEXT NOT NULL,
  school_id      UUID REFERENCES public.schools(id) ON DELETE CASCADE,
  created_at     TIMESTAMPTZ DEFAULT now(),
  UNIQUE(parent_user_id, student_id)
);

ALTER TABLE public.parent_links ENABLE ROW LEVEL SECURITY;

-- Parents see their own links
CREATE POLICY "Parents read own links"
  ON public.parent_links FOR SELECT
  USING (parent_user_id = auth.uid());

-- Admins can read/manage all links
CREATE POLICY "Admins manage parent links"
  ON public.parent_links FOR ALL
  USING (
    public.can_access_school_data(parent_links.school_id)
  );